### ISSUE TITLE
very very small issue on declaration

### ISSUE THREAD

**Issue by JoonYong-Kim** [Densaugeo/base64_arduino#1]
Hi..
I'm using your code.
So, thank you very much. :)

When I read your code, I found a small misprint.
The parameter name should be changed 'v' to 'c' on src/base64.hpp line 27.

Have a nice day~

**Comment by Densaugeo** [comment]
Interesting - apparently my tests missed it because gcc-c++ ignores the names of parameters in the declarations. I didn't know that.

Thanks for the bug report!
