### ISSUE TITLE
Compatibility w.r.t iMX RT1064 in MCUXpresso IDE

### ISSUE THREAD

**Issue by GanesanGuru** [Densaugeo/base64_arduino#13]
Hi @Densaugeo @danielbuechele ,
I'm using [MicroOCPP_Simulator](https://github.com/matth-x/MicroOcppSimulator/) and I'm trying to port to iMX RT1064 MCU as @matth-x told that it is possible. 

During the course, I got stuck in the following error, which is attached as log. Kindly do look into it and let me know where it went wrong.

I'm suspecting that the precompiled code - base64.hpp - does it work for toolchain of iMX RT1064? I'm just guessing. Let me know @danielbuechele @Densaugeo 

PS : Also @matth-x kindly do what help can be done .. :+1: 
[ArduinoJSON.log](https://github.com/Densaugeo/base64_arduino/files/13437926/ArduinoJSON.log)

**Comment by GanesanGuru** [comment]
Resolved..Hence closing it. Thanks @danielbuechele @Densaugeo  @matth-x for such a brilliant library...

**Comment by Densaugeo** [comment]
Glad to see you figured it out. Haven't touched this in a long time, but it's neat to see people still use it. Fortunately base 64 encoders don't need a lot of updates :)
