### ISSUE TITLE
Compiler complains about comparison between signed and unsigned ints

### ISSUE THREAD

**Issue by HoWol76** [Densaugeo/base64_arduino#6]
When I compile a project with this library installed, the compiler complains about line 126 in base64.hpp, specifically about

    input - start < input_length

input is always equal or larger than start, so that should never be an issue, but the compiler would like it better if it was changed to 

    (unsigned int) (input - start) < input_length

I guess.

**Comment by Densaugeo** [comment]
Interesting. What compiler are you using? I haven't seen any errors or warning with the Arduino IDE or with plain GCC.

In any case I don't see any harm in adding an explicit cast. I'll do that in a bit.

**Comment by HoWol76** [comment]
I use platformIO with VS Code. It's just a silly little compile time warning that flashes up every time I compile. It's not a show-stopper at all.

**Comment by Densaugeo** [comment]
They must have more strict warnings. Anyway, it should be gone with the new version. Thanks for reporting.
